version: '3'
# CI build images and push to registry.
services:
    backend:
        image: ${CI_REGISTRY_API_WITH_PREFIX}_container_healtheck
        build:
            context: ../../
            dockerfile: backend/Dockerfile
            args:
                - SERVICE_INTERNAL_PORT=${SERVICE_INTERNAL_PORT}
        expose:
            - ${SERVICE_INTERNAL_PORT}