version: '3'

services:
    backend:
        image: ${CI_REGISTRY_API_WITH_PREFIX}_container_healtheck
        deploy:
            #  setting deploy: mode: global ensures exactly one container task runs on every active node in the cluster.
            mode: global
#            replicas: each by 1
            endpoint_mode: dnsrr
            placement:
                constraints:
                    - node.platform.os == linux
