version: '3'

services:
    container_healtheck_manager:
        image: ${CI_REGISTRY_API_WITH_PREFIX}_container_healtheck
        deploy:
            replicas: 1
            # dnsrr - returns a list of IP addresses (DNS round-robin)
            endpoint_mode: vip
            placement:
                constraints:
                    - node.platform.os == linux
                    - node.role==manager  # worker or manager
        healthcheck:
            test: [ "CMD", "curl", "--fail", "http://localhost:${SERVICE_INTERNAL_PORT}/healthcheck/" ]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 10
        environment:
            - MODE=manager  # worker or manager
            - SERVICE_INTERNAL_PORT
            - SERVICE_UVICORN_WORKERS
        volumes:
            -  docker_socket_file:/var/run/docker.sock:ro

    container_healtheck_node:
        image: ${CI_REGISTRY_API_WITH_PREFIX}_container_healtheck
        deploy:
            #  setting deploy: mode: global ensures exactly one container task runs on every active node in the cluster.
            mode: global
            #            replicas: each by 1
            # dnsrr - returns a list of IP addresses (DNS round-robin)
            endpoint_mode: dnsrr
            placement:
                constraints:
                    - node.platform.os == linux
                    - node.role==worker
        healthcheck:
            test: [ "CMD", "curl", "--fail", "http://localhost:${SERVICE_INTERNAL_PORT}/healthcheck/" ]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 10
        environment:
            - MODE=worker  # worker or manager
            - SERVICE_INTERNAL_PORT
            - SERVICE_UVICORN_WORKERS
        volumes:
            - docker_socket_file:/var/run/docker.sock:ro

volumes:
    docker_socket_file:
        driver: local
            driver_opts:
                type: 'none'
                o: 'bind'
                device: '/var/run/docker.sock'